package com.mohsin.railway_eticket.domain;
// Generated Jul 31, 2018 10:08:19 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BookingSeat generated by hbm2java
 */
@Entity
@Table(name="booking_seat"
    ,catalog="final_project"
)
public class BookingSeat  implements java.io.Serializable {


     private Integer boSeatId;
     private Booking booking;
     private CoachInfo coachInfo;
     private int seatNo;

    public BookingSeat() {
    }

    public BookingSeat(Booking booking, CoachInfo coachInfo, int seatNo) {
       this.booking = booking;
       this.coachInfo = coachInfo;
       this.seatNo = seatNo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="bo_seat_id", unique=true, nullable=false)
    public Integer getBoSeatId() {
        return this.boSeatId;
    }
    
    public void setBoSeatId(Integer boSeatId) {
        this.boSeatId = boSeatId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="book_id", nullable=false)
    public Booking getBooking() {
        return this.booking;
    }
    
    public void setBooking(Booking booking) {
        this.booking = booking;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="coach_id", nullable=false)
    public CoachInfo getCoachInfo() {
        return this.coachInfo;
    }
    
    public void setCoachInfo(CoachInfo coachInfo) {
        this.coachInfo = coachInfo;
    }

    
    @Column(name="seat_no", nullable=false)
    public int getSeatNo() {
        return this.seatNo;
    }
    
    public void setSeatNo(int seatNo) {
        this.seatNo = seatNo;
    }




}


