package com.mohsin.railway_eticket.domain;
// Generated Jul 31, 2018 10:08:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name="booking"
    ,catalog="final_project"
)
public class Booking  implements java.io.Serializable {


     private Integer bookId;
     private CoachInfo coachInfo;
     private TrainSchedule trainSchedule;
     private User user;
     private Date bookDate;
     private String bookStatus;
     private int TBookedSeat;
     private String paymentStatus;
     private double totalPrice;
     private int ticketNumber;
     private Set<BookingSeat> bookingSeats = new HashSet<BookingSeat>(0);

    public Booking() {
    }

	
    public Booking(CoachInfo coachInfo, TrainSchedule trainSchedule, User user, Date bookDate, String bookStatus, int TBookedSeat, String paymentStatus, double totalPrice, int ticketNumber) {
        this.coachInfo = coachInfo;
        this.trainSchedule = trainSchedule;
        this.user = user;
        this.bookDate = bookDate;
        this.bookStatus = bookStatus;
        this.TBookedSeat = TBookedSeat;
        this.paymentStatus = paymentStatus;
        this.totalPrice = totalPrice;
        this.ticketNumber = ticketNumber;
    }
    public Booking(CoachInfo coachInfo, TrainSchedule trainSchedule, User user, Date bookDate, String bookStatus, int TBookedSeat, String paymentStatus, double totalPrice, int ticketNumber, Set<BookingSeat> bookingSeats) {
       this.coachInfo = coachInfo;
       this.trainSchedule = trainSchedule;
       this.user = user;
       this.bookDate = bookDate;
       this.bookStatus = bookStatus;
       this.TBookedSeat = TBookedSeat;
       this.paymentStatus = paymentStatus;
       this.totalPrice = totalPrice;
       this.ticketNumber = ticketNumber;
       this.bookingSeats = bookingSeats;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="book_id", unique=true, nullable=false)
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="coach_id", nullable=false)
    public CoachInfo getCoachInfo() {
        return this.coachInfo;
    }
    
    public void setCoachInfo(CoachInfo coachInfo) {
        this.coachInfo = coachInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="schedule_id", nullable=false)
    public TrainSchedule getTrainSchedule() {
        return this.trainSchedule;
    }
    
    public void setTrainSchedule(TrainSchedule trainSchedule) {
        this.trainSchedule = trainSchedule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="book_date", nullable=false, length=10)
    public Date getBookDate() {
        return this.bookDate;
    }
    
    public void setBookDate(Date bookDate) {
        this.bookDate = bookDate;
    }

    
    @Column(name="book_status", nullable=false, length=45)
    public String getBookStatus() {
        return this.bookStatus;
    }
    
    public void setBookStatus(String bookStatus) {
        this.bookStatus = bookStatus;
    }

    
    @Column(name="t_booked_seat", nullable=false)
    public int getTBookedSeat() {
        return this.TBookedSeat;
    }
    
    public void setTBookedSeat(int TBookedSeat) {
        this.TBookedSeat = TBookedSeat;
    }

    
    @Column(name="payment_status", nullable=false, length=50)
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    
    @Column(name="total_price", nullable=false, precision=22, scale=0)
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    
    @Column(name="ticket_number", nullable=false)
    public int getTicketNumber() {
        return this.ticketNumber;
    }
    
    public void setTicketNumber(int ticketNumber) {
        this.ticketNumber = ticketNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="booking")
    public Set<BookingSeat> getBookingSeats() {
        return this.bookingSeats;
    }
    
    public void setBookingSeats(Set<BookingSeat> bookingSeats) {
        this.bookingSeats = bookingSeats;
    }




}


