package com.mohsin.railway_eticket.domain;
// Generated Jul 31, 2018 10:08:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CoachInfo generated by hbm2java
 */
@Entity
@Table(name="coach_info"
    ,catalog="final_project"
)
public class CoachInfo  implements java.io.Serializable {


     private Integer coachId;
     private TrainInfo trainInfo;
     private String coachName;
     private String coachType;
     private String totalSeat;
     private double ticketPrice;
     private Set<BookingSeat> bookingSeats = new HashSet<BookingSeat>(0);
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public CoachInfo() {
    }

	
    public CoachInfo(TrainInfo trainInfo, String coachName, String coachType, String totalSeat, double ticketPrice) {
        this.trainInfo = trainInfo;
        this.coachName = coachName;
        this.coachType = coachType;
        this.totalSeat = totalSeat;
        this.ticketPrice = ticketPrice;
    }
    public CoachInfo(TrainInfo trainInfo, String coachName, String coachType, String totalSeat, double ticketPrice, Set<BookingSeat> bookingSeats, Set<Booking> bookings) {
       this.trainInfo = trainInfo;
       this.coachName = coachName;
       this.coachType = coachType;
       this.totalSeat = totalSeat;
       this.ticketPrice = ticketPrice;
       this.bookingSeats = bookingSeats;
       this.bookings = bookings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="coach_id", unique=true, nullable=false)
    public Integer getCoachId() {
        return this.coachId;
    }
    
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="train_id", nullable=false)
    public TrainInfo getTrainInfo() {
        return this.trainInfo;
    }
    
    public void setTrainInfo(TrainInfo trainInfo) {
        this.trainInfo = trainInfo;
    }

    
    @Column(name="coach_name", nullable=false, length=45)
    public String getCoachName() {
        return this.coachName;
    }
    
    public void setCoachName(String coachName) {
        this.coachName = coachName;
    }

    
    @Column(name="coach_type", nullable=false, length=40)
    public String getCoachType() {
        return this.coachType;
    }
    
    public void setCoachType(String coachType) {
        this.coachType = coachType;
    }

    
    @Column(name="total_seat", nullable=false, length=45)
    public String getTotalSeat() {
        return this.totalSeat;
    }
    
    public void setTotalSeat(String totalSeat) {
        this.totalSeat = totalSeat;
    }

    
    @Column(name="ticket_price", nullable=false, precision=22, scale=0)
    public double getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(double ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coachInfo")
    public Set<BookingSeat> getBookingSeats() {
        return this.bookingSeats;
    }
    
    public void setBookingSeats(Set<BookingSeat> bookingSeats) {
        this.bookingSeats = bookingSeats;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coachInfo")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


