package com.mohsin.railway_eticket.domain;
// Generated Jul 31, 2018 10:08:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Route generated by hbm2java
 */
@Entity
@Table(name="route"
    ,catalog="final_project"
)
public class Route  implements java.io.Serializable {


     private Integer routeId;
     private int routeNo;
     private String routeName;
     private String source;
     private String destination;
     private Set<RouteStation> routeStations = new HashSet<RouteStation>(0);
     private Set<TrainSchedule> trainSchedules = new HashSet<TrainSchedule>(0);

    public Route() {
    }

	
    public Route(int routeNo, String routeName, String source, String destination) {
        this.routeNo = routeNo;
        this.routeName = routeName;
        this.source = source;
        this.destination = destination;
    }
    public Route(int routeNo, String routeName, String source, String destination, Set<RouteStation> routeStations, Set<TrainSchedule> trainSchedules) {
       this.routeNo = routeNo;
       this.routeName = routeName;
       this.source = source;
       this.destination = destination;
       this.routeStations = routeStations;
       this.trainSchedules = trainSchedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="route_id", unique=true, nullable=false)
    public Integer getRouteId() {
        return this.routeId;
    }
    
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    
    @Column(name="route_no", nullable=false)
    public int getRouteNo() {
        return this.routeNo;
    }
    
    public void setRouteNo(int routeNo) {
        this.routeNo = routeNo;
    }

    
    @Column(name="route_name", nullable=false, length=45)
    public String getRouteName() {
        return this.routeName;
    }
    
    public void setRouteName(String routeName) {
        this.routeName = routeName;
    }

    
    @Column(name="source", nullable=false, length=60)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="destination", nullable=false, length=60)
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="route")
    public Set<RouteStation> getRouteStations() {
        return this.routeStations;
    }
    
    public void setRouteStations(Set<RouteStation> routeStations) {
        this.routeStations = routeStations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="route")
    public Set<TrainSchedule> getTrainSchedules() {
        return this.trainSchedules;
    }
    
    public void setTrainSchedules(Set<TrainSchedule> trainSchedules) {
        this.trainSchedules = trainSchedules;
    }




}


