package com.mohsin.railway_eticket.domain;
// Generated Jul 31, 2018 10:08:19 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RouteStation generated by hbm2java
 */
@Entity
@Table(name="route_station"
    ,catalog="final_project"
)
public class RouteStation  implements java.io.Serializable {


     private Integer stationId;
     private Route route;
     private String stationName;
     private int contactNo;

    public RouteStation() {
    }

    public RouteStation(Route route, String stationName, int contactNo) {
       this.route = route;
       this.stationName = stationName;
       this.contactNo = contactNo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="station_id", unique=true, nullable=false)
    public Integer getStationId() {
        return this.stationId;
    }
    
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="route_id", nullable=false)
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }

    
    @Column(name="station_name", nullable=false, length=45)
    public String getStationName() {
        return this.stationName;
    }
    
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    
    @Column(name="contact_no", nullable=false)
    public int getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(int contactNo) {
        this.contactNo = contactNo;
    }




}


