package com.mohsin.railway_eticket.domain;
// Generated Jul 31, 2018 10:08:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TrainInfo generated by hbm2java
 */
@Entity
@Table(name="train_info"
    ,catalog="final_project"
)
public class TrainInfo  implements java.io.Serializable {


     private Integer trainId;
     private String trainName;
     private String offDay;
     private String trainType;
     private int capacity;
     private Set<TrainSchedule> trainSchedules = new HashSet<TrainSchedule>(0);
     private Set<CoachInfo> coachInfos = new HashSet<CoachInfo>(0);

    public TrainInfo() {
    }

	
    public TrainInfo(String trainName, String offDay, String trainType, int capacity) {
        this.trainName = trainName;
        this.offDay = offDay;
        this.trainType = trainType;
        this.capacity = capacity;
    }
    public TrainInfo(String trainName, String offDay, String trainType, int capacity, Set<TrainSchedule> trainSchedules, Set<CoachInfo> coachInfos) {
       this.trainName = trainName;
       this.offDay = offDay;
       this.trainType = trainType;
       this.capacity = capacity;
       this.trainSchedules = trainSchedules;
       this.coachInfos = coachInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="train_id", unique=true, nullable=false)
    public Integer getTrainId() {
        return this.trainId;
    }
    
    public void setTrainId(Integer trainId) {
        this.trainId = trainId;
    }

    
    @Column(name="train_name", nullable=false, length=60)
    public String getTrainName() {
        return this.trainName;
    }
    
    public void setTrainName(String trainName) {
        this.trainName = trainName;
    }

    
    @Column(name="off_day", nullable=false, length=45)
    public String getOffDay() {
        return this.offDay;
    }
    
    public void setOffDay(String offDay) {
        this.offDay = offDay;
    }

    
    @Column(name="train_type", nullable=false, length=45)
    public String getTrainType() {
        return this.trainType;
    }
    
    public void setTrainType(String trainType) {
        this.trainType = trainType;
    }

    
    @Column(name="capacity", nullable=false)
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trainInfo")
    public Set<TrainSchedule> getTrainSchedules() {
        return this.trainSchedules;
    }
    
    public void setTrainSchedules(Set<TrainSchedule> trainSchedules) {
        this.trainSchedules = trainSchedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trainInfo")
    public Set<CoachInfo> getCoachInfos() {
        return this.coachInfos;
    }
    
    public void setCoachInfos(Set<CoachInfo> coachInfos) {
        this.coachInfos = coachInfos;
    }




}


