package com.mohsin.railway_eticket.domain;
// Generated Jul 31, 2018 10:08:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrainSchedule generated by hbm2java
 */
@Entity
@Table(name="train_schedule"
    ,catalog="final_project"
)
public class TrainSchedule  implements java.io.Serializable {


     private Integer scheduleId;
     private Route route;
     private TrainInfo trainInfo;
     private Date deparDate;
     private String deparTime;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public TrainSchedule() {
    }

	
    public TrainSchedule(Route route, TrainInfo trainInfo, Date deparDate, String deparTime) {
        this.route = route;
        this.trainInfo = trainInfo;
        this.deparDate = deparDate;
        this.deparTime = deparTime;
    }
    public TrainSchedule(Route route, TrainInfo trainInfo, Date deparDate, String deparTime, Set<Booking> bookings) {
       this.route = route;
       this.trainInfo = trainInfo;
       this.deparDate = deparDate;
       this.deparTime = deparTime;
       this.bookings = bookings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="schedule_id", unique=true, nullable=false)
    public Integer getScheduleId() {
        return this.scheduleId;
    }
    
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="route_id", nullable=false)
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="train_id", nullable=false)
    public TrainInfo getTrainInfo() {
        return this.trainInfo;
    }
    
    public void setTrainInfo(TrainInfo trainInfo) {
        this.trainInfo = trainInfo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="depar_date", nullable=false, length=10)
    public Date getDeparDate() {
        return this.deparDate;
    }
    
    public void setDeparDate(Date deparDate) {
        this.deparDate = deparDate;
    }

    
    @Column(name="depar_time", nullable=false, length=30)
    public String getDeparTime() {
        return this.deparTime;
    }
    
    public void setDeparTime(String deparTime) {
        this.deparTime = deparTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trainSchedule")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


