package com.mohsin.railway_eticket.domain;
// Generated Jul 31, 2018 10:08:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="final_project"
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private UserType userType;
     private String userName;
     private String userPass;
     private int userPhone;
     private String userEmail;
     private String userAddress;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public User() {
    }

	
    public User(UserType userType, String userName, String userPass, int userPhone, String userEmail, String userAddress) {
        this.userType = userType;
        this.userName = userName;
        this.userPass = userPass;
        this.userPhone = userPhone;
        this.userEmail = userEmail;
        this.userAddress = userAddress;
    }
    public User(UserType userType, String userName, String userPass, int userPhone, String userEmail, String userAddress, Set<Booking> bookings) {
       this.userType = userType;
       this.userName = userName;
       this.userPass = userPass;
       this.userPhone = userPhone;
       this.userEmail = userEmail;
       this.userAddress = userAddress;
       this.bookings = bookings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="u_type_id", nullable=false)
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    
    @Column(name="user_name", nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_pass", nullable=false, length=45)
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    
    @Column(name="user_phone", nullable=false)
    public int getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(int userPhone) {
        this.userPhone = userPhone;
    }

    
    @Column(name="user_email", nullable=false, length=50)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="user_address", nullable=false, length=50)
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


